module.exports.groups = [
    { group_name: "MAIN ASSETS", group_code: 1, parent_code: null, type: 'Balance Sheet', isPredefinedGroup: true },
    { group_name: "GENERAL GROUP", group_code: 2, parent_code: null, type: 'Balance Sheet', isPredefinedGroup: true },
    { group_name: "PURCHASE A/C", group_code: 3, parent_code: null, type: 'Balance Sheet', isPredefinedGroup: true },
    { group_name: "SALE A/C", group_code: 4, parent_code: null, type: 'Balance Sheet', isPredefinedGroup: true },
    { group_name: "SUNDRY CREDITORS", group_code: 5, parent_code: null, type: 'Balance Sheet', isPredefinedGroup: true },
    { group_name: "BANK", group_code: 6, parent_code: null, type: 'Balance Sheet', isPredefinedGroup: true },
    { group_name: "SUNDRY DEBTORS", group_code: 7, parent_code: null, type: 'Balance Sheet', isPredefinedGroup: true },
    { group_name: "EXPENSES", group_code: 8, parent_code: null, type: 'P&L', isPredefinedGroup: true },
    { group_name: "CURRENT ASSETS", group_code: 9, parent_code: null, type: 'Balance Sheet', isPredefinedGroup: true },
    { group_name: "CURRENT LIABILITIES", group_code: 10, parent_code: null, type: 'Balance Sheet', isPredefinedGroup: true },
    { group_name: "CAPITAL A/C", group_code: 11, parent_code: null, type: 'Balance Sheet', isPredefinedGroup: true },
    { group_name: "FIXED ASSETS", group_code: 12, parent_code: null, type: 'Balance Sheet', isPredefinedGroup: true },
    { group_name: "SECURED LOANS", group_code: 13, parent_code: null, type: 'Balance Sheet', isPredefinedGroup: true },
    { group_name: "UNSECURED LOANS", group_code: 14, parent_code: null, type: 'Balance Sheet', isPredefinedGroup: true },
    { group_name: "PARTNERS/PROPERITOR", group_code: 15, parent_code: null, type: 'Balance Sheet', isPredefinedGroup: true },
    { group_name: "SECURITIES", group_code: 16, parent_code: null, type: 'Balance Sheet', isPredefinedGroup: true },
    { group_name: "OTHERS PAYABLE", group_code: 17, parent_code: null, type: 'Balance Sheet', isPredefinedGroup: true },
    { group_name: "OTHERS RECEIVABLE", group_code: 18, parent_code: null, type: 'Balance Sheet', isPredefinedGroup: true },
    { group_name: "DISTRIBUTORS, C & F", group_code: 19, parent_code: null, type: 'Balance Sheet', isPredefinedGroup: true },
    { group_name: "INVESTMENTS", group_code: 20, parent_code: null, type: 'Balance Sheet', isPredefinedGroup: true },
    { group_name: "INCOME", group_code: 21, parent_code: null, type: 'P&L', isPredefinedGroup: true },
    { group_name: "PROVISIONS", group_code: 22, parent_code: null, type: 'Balance Sheet', isPredefinedGroup: true },
    { group_name: "DUTIES & TAXES", group_code: 23, parent_code: null, type: 'Balance Sheet', isPredefinedGroup: true }
  ];