module.exports.PartyList = [
    { party_name: "General Ledger", account_group: "SUNDRY DEBTORS"},
    { party_name: "TCS on Purchase",account_group: "CURRENT ASSETS"},
    { party_name: "CGST Input", account_group: "DUTIES & TAXES"},
    { party_name: "CGST Input (RCM)",account_group: "DUTIES & TAXES"},
    { party_name: "CGST Output", account_group: "DUTIES & TAXES"},
    { party_name: "CGST Output (RCM)", account_group: "DUTIES & TAXES"},
    { party_name: "Cess Input (RCM)", account_group: "DUTIES & TAXES"},
    { party_name: "Cess Output (RCM)", account_group: "DUTIES & TAXES"},
    { party_name: "Cess on GST Input", account_group: "DUTIES & TAXES"},
    { party_name: "Cess on GST Output", account_group: "DUTIES & TAXES"},
    { party_name: "GST Payable (CGST)", account_group: "DUTIES & TAXES"},
    { party_name: "GST Payable (IGST)", account_group: "DUTIES & TAXES"},
    { party_name: "GST Payable (SGST)", account_group: "DUTIES & TAXES"},
    { party_name: "GST Recievable (CGST)", account_group: "DUTIES & TAXES"},
    { party_name: "GST Recievable (IGST)", account_group: "DUTIES & TAXES"},
    { party_name: "GST Recievable (SGST)", account_group: "DUTIES & TAXES"},
    { party_name: "IGST Input", account_group: "DUTIES & TAXES"},
    { party_name: "IGST Input (RCM)", account_group: "DUTIES & TAXES"},
    { party_name: "IGST Output", account_group: "DUTIES & TAXES"},
    { party_name: "IGST Output (RCM)", account_group: "DUTIES & TAXES"},
    { party_name: "Input VAT", account_group: "DUTIES & TAXES"},
    { party_name: "Output VAT", account_group: "DUTIES & TAXES"},
    { party_name: "SGST Input", account_group: "DUTIES & TAXES"},
    { party_name: "SGST Output", account_group: "DUTIES & TAXES"},
    { party_name: "SGST Output (RCM)", account_group: "DUTIES & TAXES"},
    { party_name: "SGST Input (RCM)", account_group: "DUTIES & TAXES"},
    { party_name: "TCS on Good Sold", account_group: "DUTIES & TAXES"},
    { party_name: "TDS on Purchase", account_group: "DUTIES & TAXES"},      
    { party_name: "Deamed Export Sale", account_group: "SALE A/C"},
    { party_name: "Export Sale", account_group: "SALE A/C"},
    { party_name: "SEZ Sale", account_group: "SALE A/C"},
    { party_name: "Sales Tax Free", account_group: "SALE A/C"},
    { party_name: "Sales Tax Paid", account_group: "SALE A/C"},
    { party_name: "Sales", account_group: "SALE A/C"},
    { party_name: "Sales Branch Transfer", account_group: "SALE A/C"},
    { party_name: "Import Purchase", account_group: "PURCHASE A/C"},
    { party_name: "Purchase", account_group: "PURCHASE A/C"},
    { party_name: "Purchase Tax Free", account_group: "PURCHASE A/C"},
    { party_name: "Purchase Tax Paid", account_group: "PURCHASE A/C"},
    { party_name: "Purchase Branch Transfer", account_group: "PURCHASE A/C"},
    { party_name: "SEZ Purchase", account_group: "PURCHASE A/C"},
]