module.exports.PartyList = [
    { party_name: "General Ledger", account_code: null, account_group: "SUNDRY DEBTORS", isPredefinedLedger: true},
    { party_name: "TCS on Purchase",account_code: null, account_group: "CURRENT ASSETS", isPredefinedLedger: true},
    { party_name: "CGST Input", account_code: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "CGST Input (RCM)",account_code: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "CGST Output", account_code: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "CGST Output (RCM)", account_code: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "Cess Input (RCM)", account_code: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "Cess Output (RCM)", account_code: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "Cess on GST Input", account_code: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "Cess on GST Output", account_code: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "GST Payable (CGST)", account_code: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "GST Payable (IGST)", account_code: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "GST Payable (SGST)", account_code: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "GST Recievable (CGST)", account_code: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "GST Recievable (IGST)", account_code: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "GST Recievable (SGST)", account_code: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "IGST Input", account_code: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "IGST Input (RCM)", account_code: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "IGST Output", account_code: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "IGST Output (RCM)", account_code: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "Input VAT", account_code: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "Output VAT", account_code: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "SGST Input", account_code: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "SGST Output", account_code: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "SGST Output (RCM)", account_code: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "SGST Input (RCM)", account_code: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "TCS on Good Sold", account_code: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "TDS on Purchase", account_code: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},      
    { party_name: "Deamed Export Sale", account_code: null, account_group: "SALE A/C", isPredefinedLedger: true},
    { party_name: "Export Sale", account_code: null, account_group: "SALE A/C", isPredefinedLedger: true},
    { party_name: "SEZ Sale", account_code: null, account_group: "SALE A/C", isPredefinedLedger: true},
    { party_name: "Sales Tax Free", account_code: null, account_group: "SALE A/C", isPredefinedLedger: true},
    { party_name: "Sales Tax Paid", account_code: null, account_group: "SALE A/C", isPredefinedLedger: true},
    { party_name: "Sales", account_code: null, account_group: "SALE A/C", isPredefinedLedger: true},
    { party_name: "Sales Branch Transfer", account_code: null, account_group: "SALE A/C", isPredefinedLedger: true},
    { party_name: "Import Purchase", account_code: null, account_group: "PURCHASE A/C", isPredefinedLedger: true},
    { party_name: "Purchase", account_code: null, account_group: "PURCHASE A/C", isPredefinedLedger: true},
    { party_name: "Purchase Tax Free", account_code: null, account_group: "PURCHASE A/C", isPredefinedLedger: true},
    { party_name: "Purchase Tax Paid", account_code: null, account_group: "PURCHASE A/C", isPredefinedLedger: true},
    { party_name: "Purchase Branch Transfer", account_code: null, account_group: "PURCHASE A/C", isPredefinedLedger: true},
    { party_name: "SEZ Purchase", account_code: null, account_group: "PURCHASE A/C", isPredefinedLedger: true},
]