module.exports.PartyList = [
    { party_name: "General Ledger", accountCode: null, account_group: "SUNDRY DEBTORS", isPredefinedLedger: true},
    { party_name: "TCS on Purchase",accountCode: null, account_group: "CURRENT ASSETS", isPredefinedLedger: true},
    { party_name: "CGST Input", accountCode: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "CGST Input (RCM)",accountCode: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "CGST Output", accountCode: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "CGST Output (RCM)", accountCode: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "Cess Input (RCM)", accountCode: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "Cess Output (RCM)", accountCode: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "Cess on GST Input", accountCode: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "Cess on GST Output", accountCode: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "GST Payable (CGST)", accountCode: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "GST Payable (IGST)", accountCode: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "GST Payable (SGST)", accountCode: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "GST Recievable (CGST)", accountCode: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "GST Recievable (IGST)", accountCode: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "GST Recievable (SGST)", accountCode: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "IGST Input", accountCode: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "IGST Input (RCM)", accountCode: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "IGST Output", accountCode: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "IGST Output (RCM)", accountCode: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "Input VAT", accountCode: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "Output VAT", accountCode: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "SGST Input", accountCode: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "SGST Output", accountCode: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "SGST Output (RCM)", accountCode: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "SGST Input (RCM)", accountCode: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "TCS on Good Sold", accountCode: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},
    { party_name: "TDS on Purchase", accountCode: null, account_group: "DUTIES & TAXES", isPredefinedLedger: true},      
    { party_name: "Deamed Export Sale", accountCode: null, account_group: "SALE A/C", isPredefinedLedger: true},
    { party_name: "Export Sale", accountCode: null, account_group: "SALE A/C", isPredefinedLedger: true},
    { party_name: "SEZ Sale", accountCode: null, account_group: "SALE A/C", isPredefinedLedger: true},
    { party_name: "Sales Tax Free", accountCode: null, account_group: "SALE A/C", isPredefinedLedger: true},
    { party_name: "Sales Tax Paid", accountCode: null, account_group: "SALE A/C", isPredefinedLedger: true},
    { party_name: "Sales", accountCode: null, account_group: "SALE A/C", isPredefinedLedger: true},
    { party_name: "Sales Branch Transfer", accountCode: null, account_group: "SALE A/C", isPredefinedLedger: true},
    { party_name: "Import Purchase", accountCode: null, account_group: "PURCHASE A/C", isPredefinedLedger: true},
    { party_name: "Purchase", accountCode: null, account_group: "PURCHASE A/C", isPredefinedLedger: true},
    { party_name: "Purchase Tax Free", accountCode: null, account_group: "PURCHASE A/C", isPredefinedLedger: true},
    { party_name: "Purchase Tax Paid", accountCode: null, account_group: "PURCHASE A/C", isPredefinedLedger: true},
    { party_name: "Purchase Branch Transfer", accountCode: null, account_group: "PURCHASE A/C", isPredefinedLedger: true},
    { party_name: "SEZ Purchase", accountCode: null, account_group: "PURCHASE A/C", isPredefinedLedger: true},
]