module.exports.statesList = [
    { state_name: "Andaman and Nicobar Islands", state_code: 35, union_territory: true},
    { state_name: "Andhra Pradesh", state_code: 28,union_territory: false},
    { state_name: "ANDHRA PRADESH (NEW)", state_code: 37, union_territory: false},
    { state_name: "Arunachal Pradesh", state_code: 12, union_territory: false},
    { state_name: "Assam", state_code: 18, union_territory: false},
    { state_name: "Bihar", state_code: 10, union_territory: false},
    { state_name: "Chandigarh", state_code: 4, union_territory: true},
    { state_name: "Chattisgarh", state_code: 22, union_territory: false},
    { state_name: "Dadra and Nagar Haveli", state_code: 26, union_territory: true},
    { state_name: "Daman and Diu", state_code: 25, union_territory: true},
    { state_name: "Delhi", state_code: 7, union_territory: false},
    { state_name: "Goa", state_code: 30, union_territory: false},
    { state_name: "Gujarat", state_code: 24, union_territory: false},
    { state_name: "Haryana", state_code: 6, union_territory: false},
    { state_name: "Himachal Pradesh", state_code: 2, union_territory: false},
    { state_name: "Jammu and Kashmir", state_code: 1, union_territory: false},
    { state_name: "Jharkhand", state_code: 20, union_territory: false},
    { state_name: "Karnataka", state_code: 29, union_territory: false},
    { state_name: "Kerala", state_code: 32, union_territory: false},
    { state_name: "Lakshadweep Islands", state_code: 31, union_territory: true},
    { state_name: "Madhya Pradesh", state_code: 23, union_territory: false},
    { state_name: "Maharashtra", state_code: 27, union_territory: false},
    { state_name: "Manipur", state_code: 14, union_territory: false},
    { state_name: "Meghalaya", state_code: 17, union_territory: false},
    { state_name: "Mizoram", state_code: 15, union_territory: false},
    { state_name: "Nagaland", state_code: 13, union_territory: false},
    { state_name: "Odisha", state_code: 21, union_territory: false},
    { state_name: "Pondichery", state_code: 34, union_territory: true},
    { state_name: "Punjab", state_code: 3, union_territory: false},
    { state_name: "Rajasthan", state_code: 8, union_territory: false},
    { state_name: "Sikkim", state_code: 11, union_territory: false},
    { state_name: "Tamil Nadu", state_code: 33, union_territory: false},
    { state_name: "Telangana", state_code: 36, union_territory: false},
    { state_name: "Tripura", state_code: 16, union_territory: false},
    { state_name: "Uttar Pradesh", state_code: 9, union_territory: false},
    { state_name: "Uttarakhand", state_code: 5, union_territory: false},
    { state_name: "West Bengal", state_code: 19, union_territory: false},                                   
]